---
- name: Activer le routage IP (net.ipv4.ip_forward)
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes


- name: Initialiser le cluster Kubernetes (master)
  become: true
  ansible.builtin.command: kubeadm init --pod-network-cidr={{ pod_network_cidr }} --ignore-preflight-errors=NumCPU,Mem,CRI
  args:
    creates: /etc/kubernetes/admin.conf


- name: Créer le dossier .kube
  become: true
  ansible.builtin.file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'

- name: Copier la config admin.conf dans ~/.kube/config
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: /home/ubuntu/.kube/config
    remote_src: true
    owner: ubuntu
    group: ubuntu
    mode: '0600'

- name: Déployer l'application Node.js
  import_tasks: deploy_app.yml

